/**
 * This file was auto-generated by a Deno script.
 * Please do not edit this file directly.
 *
 * Generated at: 2025-09-13T13:48:43.651Z
 */

export interface Level {
  /** @db_type int4 */
  id: number;
  /** @db_type int4 */
  geometry_dash_id: number;
  /** @db_type leveltype */
  type: any;
  /** @db_type text */
  name: string;
  /** @db_type text */
  publisher: string;
  /** @db_type int4 */
  publisher_id: number | null;
  /** @db_type text */
  description: string | null;
  /** @db_type leveldifficulty */
  difficulty: any;
  /** @db_type levellength */
  length: any | null;
  /** @db_type int4 */
  song_id: number | null;
  /** @db_type date */
  release_date: Date | null;
  /** @db_type text */
  video_url: string | null;
  /** @db_type timestamp */
  created_at: Date;
}

export interface Progress {
  /** @db_type int4 */
  id: number;
  /** @db_type int4 */
  user_id: number | null;
  /** @db_type int4 */
  level_id: number | null;
  /** @db_type progressstatus */
  status: any;
  /** @db_type int2 */
  completion_pct: number | null;
  /** @db_type int4 */
  completion_time: number | null;
  /** @db_type int4 */
  total_attempts: number | null;
  /** @db_type date */
  start_date: Date | null;
  /** @db_type date */
  complete_date: Date | null;
  /** @db_type int2 */
  enjoyment_rating: number | null;
  /** @db_type text */
  video_url: string | null;
  /** @db_type text */
  review: string | null;
  /** @db_type timestamp */
  created_at: Date;
  /** @db_type timestamp */
  updated_at: Date;
}

export interface Song {
  /** @db_type int4 */
  id: number;
  /** @db_type int4 */
  geometry_dash_id: number;
  /** @db_type text */
  title: string;
  /** @db_type text */
  artist: string;
  /** @db_type timestamp */
  created_at: Date;
}

export interface User {
  /** @db_type int4 */
  id: number;
  /** @db_type text */
  username: string;
  /** @db_type text */
  email: string;
  /** @db_type text */
  password_hash: string;
  /** @db_type text */
  bio: string | null;
  /** @db_type text */
  profile_picture_url: string | null;
  /** @db_type timestamp */
  created_at: Date;
}

