import type { OfficialSong, Level } from "./types";

export const songs: Record<number, OfficialSong> = {
  0: { id: 0, name: "Stereo Madness", artist: { name: "Foreverbound" } },
  1: { id: 1, name: "Back on Track", artist: { name: "DJVI" } },
  2: { id: 2, name: "Polargeist", artist: { name: "Step" } },
  3: { id: 3, name: "Dry Out", artist: { name: "DJVI" } },
  4: { id: 4, name: "Base after Base", artist: { name: "DJVI" } },
  5: { id: 5, name: "Cant Let Go", artist: { name: "DJVI" } },
  6: { id: 6, name: "Jumper", artist: { name: "Waterflame" } },
  7: { id: 7, name: "Time Machine", artist: { name: "Waterflame" } },
  8: { id: 8, name: "Cycles", artist: { name: "DJVI" } },
  9: { id: 9, name: "xStep", artist: { name: "DJVI" } },
  10: { id: 10, name: "Clutterfunk", artist: { name: "Waterflame" } },
  11: { id: 11, name: "Theory of Everything", artist: { name: "DJ-Nate" } },
  12: { id: 12, name: "Electroman Adventures", artist: { name: "Waterflame" } },
  13: { id: 13, name: "Clubstep", artist: { name: "DJ-Nate" } },
  14: { id: 14, name: "Electrodynamix", artist: { name: "DJ-Nate" } },
  15: { id: 15, name: "Hexagon Force", artist: { name: "Waterflame" } },
  16: { id: 16, name: "Blast Processing", artist: { name: "Waterflame" } },
  17: { id: 17, name: "Theory of Everything 2", artist: { name: "DJ-Nate" } },
  18: { id: 18, name: "Geometrical Dominator", artist: { name: "Waterflame" } },
  19: { id: 19, name: "Deadlocked", artist: { name: "F-777" } },
  20: { id: 20, name: "Fingerdash", artist: { name: "MDK" } },
  21: { id: 21, name: "Dash", artist: { name: "MDK" } },
  22: { id: 22, name: "Explorers", artist: { name: "Hinkik" } },
  23: { id: 23, name: "The Seven Seas", artist: { name: "F-777" } },
  24: { id: 24, name: "Viking Arena", artist: { name: "F-777" } },
  25: { id: 25, name: "Airborne Robots", artist: { name: "F-777" } },
  26: { id: 26, name: "Secret", artist: { name: "RobTop" } },
  27: { id: 27, name: "Payload", artist: { name: "Dex Arson" } },
  28: { id: 28, name: "Beast Mode", artist: { name: "Dex Arson" } },
  29: { id: 29, name: "Machina", artist: { name: "Dex Arson" } },
  30: { id: 30, name: "Years", artist: { name: "Dex Arson" } },
  31: { id: 31, name: "Frontlines", artist: { name: "Dex Arson" } },
  32: { id: 32, name: "Space Pirates", artist: { name: "Waterflame" } },
  33: { id: 33, name: "Striker", artist: { name: "Waterflame" } },
  34: { id: 34, name: "Embers", artist: { name: "Dex Arson" } },
  35: { id: 35, name: "Round 1", artist: { name: "Dex Arson" } },
  36: { id: 36, name: "Monster Dance Off", artist: { name: "F-777" } },
  37: { id: 37, name: "Press Start", artist: { name: "MDK" } },
  38: { id: 38, name: "Nock Em", artist: { name: "Bossfight" } },
  39: { id: 39, name: "Power Trip", artist: { name: "Boom Kitty" } },
};

const ROBTOP_CREATOR = { userId: 1, username: "RobTop", accountId: 71 };

export const levels: Record<number, Level> = {
  1: {
    id: 1,
    name: "Stereo Madness",
    versions: { level: 1, game: 10 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 1, starsRequests: 0 },
    difficulty: "easy",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[0],
  },
  2: {
    id: 2,
    name: "Back on Track",
    versions: { level: 1, game: 10 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 2, starsRequests: 0 },
    difficulty: "easy",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[1],
  },
  3: {
    id: 3,
    name: "Polargeist",
    versions: { level: 1, game: 10 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 3, starsRequests: 0 },
    difficulty: "normal",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[2],
  },
  4: {
    id: 4,
    name: "Dry Out",
    versions: { level: 1, game: 10 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 4, starsRequests: 0 },
    difficulty: "normal",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[3],
  },
  5: {
    id: 5,
    name: "Base After Base",
    versions: { level: 1, game: 10 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 5, starsRequests: 0 },
    difficulty: "hard",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[4],
  },
  6: {
    id: 6,
    name: "Can't Let Go",
    versions: { level: 1, game: 10 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 6, starsRequests: 0 },
    difficulty: "hard",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[5],
  },
  7: {
    id: 7,
    name: "Jumper",
    versions: { level: 1, game: 10 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 7, starsRequests: 0 },
    difficulty: "harder",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[6],
  },
  8: {
    id: 8,
    name: "Time Machine",
    versions: { level: 1, game: 10 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 8, starsRequests: 0 },
    difficulty: "harder",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[7],
  },
  9: {
    id: 9,
    name: "Cycles",
    versions: { level: 1, game: 11 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 9, starsRequests: 0 },
    difficulty: "harder",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[8],
  },
  10: {
    id: 10,
    name: "xStep",
    versions: { level: 1, game: 11 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 10, starsRequests: 0 },
    difficulty: "insane",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[9],
  },
  11: {
    id: 11,
    name: "Clutterfunk",
    versions: { level: 1, game: 12 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 11, starsRequests: 0 },
    difficulty: "insane",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[10],
  },
  12: {
    id: 12,
    name: "Theory of Everything",
    versions: { level: 1, game: 12 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 12, starsRequests: 0 },
    difficulty: "insane",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[11],
  },
  13: {
    id: 13,
    name: "Electroman Adventures",
    versions: { level: 1, game: 13 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 10, starsRequests: 0 },
    difficulty: "insane",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[12],
  },
  14: {
    id: 14,
    name: "Clubstep",
    versions: { level: 1, game: 14 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 14, starsRequests: 0 },
    difficulty: "demon",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[13],
  },
  15: {
    id: 15,
    name: "Electrodynamix",
    versions: { level: 1, game: 15 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 12, starsRequests: 0 },
    difficulty: "insane",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[14],
  },
  16: {
    id: 16,
    name: "Hexagon Force",
    versions: { level: 1, game: 16 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 12, starsRequests: 0 },
    difficulty: "insane",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[15],
  },
  17: {
    id: 17,
    name: "Blast Processing",
    versions: { level: 1, game: 17 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 10, starsRequests: 0 },
    difficulty: "harder",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[16],
  },
  18: {
    id: 18,
    name: "Theory of Everything 2",
    versions: { level: 1, game: 18 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 14, starsRequests: 0 },
    difficulty: "demon",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[17],
  },
  19: {
    id: 19,
    name: "Geometrical Dominator",
    versions: { level: 1, game: 19 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 10, starsRequests: 0 },
    difficulty: "harder",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[18],
  },
  20: {
    id: 20,
    name: "Deadlocked",
    versions: { level: 1, game: 20 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 15, starsRequests: 0 },
    difficulty: "demon",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[19],
  },
  21: {
    id: 21,
    name: "Fingerdash",
    versions: { level: 1, game: 21 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 12, starsRequests: 0 },
    difficulty: "insane",
    length: "long",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[20],
  },
  22: {
    id: 22,
    name: "Dash",
    versions: { level: 1, game: 22 },
    creator: ROBTOP_CREATOR,
    stats: { downloads: 0, likes: 0, dislikes: 0, stars: 12, starsRequests: 0 },
    difficulty: "insane",
    length: "xl",
    rating: "star",
    coins: { count: 3, verified: true },
    twoPlayer: false,
    song: songs[21],
  },
};
