import postgres from "postgres";

// --- CONFIGURATION ---
// Replace with your actual database connection details.
// For better security, consider using environment variables.
const DB_CONFIG = {
  hostname: "localhost",
  port: 5432,
  user: "postgres",
  password: "admin12345",
  database: "loggd",
  // Use 'require' for local development if you don't have SSL configured.
  // In production, prefer 'verify-full' with a CA certificate.
  // ssl: "require" as const,
};

const OUTPUT_FILE = "./src/lib/db-types.ts";
const SCHEMA_NAME = "public"; // The database schema to inspect.

// --- TYPE MAPPING ---
/**
 * Maps PostgreSQL data types to TypeScript types.
 * @param udtName The PostgreSQL UDT (User-Defined Type) name from information_schema.
 * @returns The corresponding TypeScript type as a string.
 */
function pgTypeToTsType(udtName: string): string {
  // Handle array types (which start with an underscore)
  if (udtName.startsWith("_")) {
    const baseType = udtName.substring(1);
    return `${pgTypeToTsType(baseType)}[]`;
  }

  switch (udtName.toLowerCase()) {
    case "int2":
    case "int4":
    case "int8":
    case "float4":
    case "float8":
    case "numeric":
    case "money":
    case "oid":
      return "number";

    case "varchar":
    case "text":
    case "char":
    case "bpchar": // Blank-padded char
    case "uuid":
    case "inet":
    case "citext": // A common case-insensitive text extension
      return "string";

    case "bool":
      return "boolean";

    case "date":
    case "timestamp":
    case "timestamptz":
      return "Date"; // Using string is often safer for serialization (e.g., JSON). Can also be 'Date'.

    case "json":
    case "jsonb":
      return "any"; // Or a more specific type like 'Record<string, any>' or a generic 'Json' type.

    case "bytea":
      return "Uint8Array";

    default:
      console.warn(
        `[Warning] Unknown PostgreSQL type: ${udtName}. Falling back to 'any'.`,
      );
      return "any";
  }
}

// --- UTILITY FUNCTIONS ---
/**
 * Converts a snake_case or kebab-case string to PascalCase.
 * @example toPascalCase('user_profile') -> 'UserProfile'
 */
function toPascalCase(str: string): string {
  return str
    .split(/_|-/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}

/**
 * A simple singularization function. Works for basic plurals ending in 's'.
 * @example singularize('users') -> 'user'
 */
function singularize(str: "string"): string {
  if (str.toLowerCase().endsWith("ies")) {
    return str.slice(0, -3) + "y";
  }
  if (str.toLowerCase().endsWith("s") && !str.toLowerCase().endsWith("ss")) {
    return str.slice(0, -1);
  }
  return str;
}

// --- MAIN LOGIC ---
async function main() {
  console.log(`Connecting to database "${DB_CONFIG.db}"...`);
  const sql = postgres(DB_CONFIG);

  try {
    // Query to get all columns, their types, and nullability for a given schema.
    const columns = await sql`
      SELECT
        table_name,
        column_name,
        udt_name,
        is_nullable
      FROM
        information_schema.columns
      WHERE
        table_schema = ${SCHEMA_NAME}
      ORDER BY
        table_name,
        ordinal_position;
    `;

    if (columns.length === 0) {
      console.log(`No tables found in schema "${SCHEMA_NAME}". Exiting.`);
      return;
    }

    console.log(
      `Found ${columns.length} columns in ${new Set(columns.map((c) => c.table_name)).size} tables.`,
    );

    // Group columns by table name
    const tables: Record<string, any[]> = {};
    for (const col of columns) {
      if (!tables[col.table_name]) {
        tables[col.table_name] = [];
      }
      tables[col.table_name].push(col);
    }

    // Generate the TypeScript interface definitions
    let typeDefs = `/**
 * This file was auto-generated by a Deno script.
 * Please do not edit this file directly.
 *
 * Generated at: ${new Date().toISOString()}
 */\n\n`;

    for (const tableName in tables) {
      const interfaceName = toPascalCase(singularize(tableName));
      typeDefs += `export interface ${interfaceName} {\n`;

      const tableColumns = tables[tableName];
      for (const col of tableColumns) {
        const tsType = pgTypeToTsType(col.udt_name);
        const isNullable = col.is_nullable === "YES";

        // Add a JSDoc comment for the property
        typeDefs += `  /** @db_type ${col.udt_name} */\n`;
        // Define the property, making it optional if nullable
        typeDefs += `  ${col.column_name}: ${tsType}${isNullable ? " | null" : ""};\n`;
      }
      typeDefs += "}\n\n";
    }

    // Write the generated types to the output file
    await Deno.writeTextFile(OUTPUT_FILE, typeDefs);
    console.log(`✅ Successfully generated types and saved to ${OUTPUT_FILE}`);
  } catch (error) {
    console.error("An error occurred during type generation:");
    console.error(error);
  } finally {
    // Ensure the database connection is always closed.
    await sql.end();
    console.log("Database connection closed.");
  }
}

// Run the main function
main();
